registryStorage:
  provider: file
    location: ~/muse-storage/registry
staticStorage:
  provider: file
  options:
    location: ~/muse-storage/static
    maxAge:
    maxSize:
cacheStorage:
  provider: @ebay/muse-nukv-cache
  options:
    token: $env.MUSE_NUKV_TOKEN
