import logo from './logo.png';

const loadingSvg = `
<?xml version="1.0" encoding="utf-8"?>
<svg style=" display: block; shape-rendering: auto;" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<path d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50" fill="#00b4d8" stroke="none">
  <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 51;360 50 51"></animateTransform>
</path>
<!-- [ldio] generated by https://loading.io/ --></svg>
`;
export default {
  init() {
    const loadingDiv = document.createElement('div');
    loadingDiv.innerHTML = `
    <div>
      <div class='muse-loading-node-inner'>
      ${loadingSvg}<img src="${logo}"/>
      </div>
      <label>Starting...</label>
    </div>
    `;
    loadingDiv.id = 'muse-loading-node';

    document.body.appendChild(loadingDiv);
    this.mountNode = loadingDiv;
    this.labelNode = loadingDiv.querySelector('label');
  },

  hide() {
    document.body.removeChild(this.mountNode);
  },

  showMessage(msg) {
    this.labelNode.innerHTML = msg || '';
  },
};
