import { register } from '@ebay/nice-modal-react';
import CreateAppModal from './features/am/CreateAppModal';
import EditAppModal from './features/am/EditAppModal';
import EditAppVariablesModal from './features/am/EditAppVariablesModal';
import EditPluginVariablesModal from './features/am/EditPluginVariablesModal';
import DeployPluginModal from './features/pm/DeployPluginModal';
import RequestDetailModal from './features/req/RequestDetailModal';
import CreatePluginModal from './features/pm/CreatePluginModal';
import EditPluginModal from './features/pm/EditPluginModal';
import ReleasesDrawer from './features/pm/ReleasesDrawer';
import EditEnvironmentModal from './features/am/EditEnvironmentModal';
import PreviewModal from './features/pm/PreviewModal';

register('muse-manager.create-app-modal', CreateAppModal);
register('muse-manager.edit-app-modal', EditAppModal);
register('muse-manager.deploy-plugin-modal', DeployPluginModal);
register('muse-manager.request-detail-modal', RequestDetailModal);
register('muse-manager.create-plugin-modal', CreatePluginModal);
register('muse-manager.edit-plugin-modal', EditPluginModal);
register('muse-manager.releases-drawer', ReleasesDrawer);
register('muse-manager.edit-environment-modal', EditEnvironmentModal);
register('muse-manager.preview-modal', PreviewModal);
register('muse-manager.edit-app-variables-modal', EditAppVariablesModal);
register('muse-manager.edit-plugin-variables-modal', EditPluginVariablesModal);
