export const MUSE_ANTD$COMMON_SET_NICE_MODAL_VISIBLE = 'MUSE_ANTD$COMMON_SET_NICE_MODAL_VISIBLE';
export const EBAY_MUSE_LIB_ANTD$COMMON_SET_IS_DARK_MODE =
  'EBAY_MUSE_LIB_ANTD$COMMON_SET_IS_DARK_MODE';
