export const MUSE_LAYOUT$HOME_SET_SIDER_COLLAPSED = 'MUSE_LAYOUT$HOME_SET_SIDER_COLLAPSED';
export const MUSE_LAYOUT$HOME_SET_LAYOUT_CONFIG = 'MUSE_LAYOUT$HOME_SET_LAYOUT_CONFIG';
export const MUSE_LAYOUT$HOME_UPDATE_MUSE_LAYOUT = 'MUSE_LAYOUT$HOME_UPDATE_MUSE_LAYOUT';
