export const MUSE_LAYOUT$HOME_SET_SIDER_COLLAPSED = 'MUSE_LAYOUT$HOME_SET_SIDER_COLLAPSED';
export const MUSE_LAYOUT$HOME_SET_LAYOUT_CONFIG = 'MUSE_LAYOUT$HOME_SET_LAYOUT_CONFIG';
export const MUSE_LAYOUT$HOME_UPDATE_MUSE_LAYOUT = 'MUSE_LAYOUT$HOME_UPDATE_MUSE_LAYOUT';
export const EBAY_MUSE_LAYOUT_ANTD$HOME_SET_IS_DARK_MODE = 'EBAY_MUSE_LAYOUT_ANTD$HOME_SET_IS_DARK_MODE';
