name: build

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - release

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.13.0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run Tests
        run: |
          export MUSE_TESTS_FLAG_RESET_PNPM_LOCK=1
          cd muse-ci-tools
          pnpm i
          pnpm test

      # after test success, publish packages to the registry
      - name: Publish Packages
        run: |
          cd muse-ci-tools
          pnpm run publish-packages
        if: ${{ github.ref_name == 'release' }}
